11/18/2023 03:15:41 PM INFO: problem_path: /home/avs/Projects/TECHAZTRA/Server/static/rounds/round_1/problem.c, problem_language: c
11/18/2023 03:15:41 PM INFO: Selected Language: C
11/18/2023 03:15:41 PM INFO: Successfully compiled problem
11/18/2023 03:15:41 PM INFO: Platform: UNIX
11/18/2023 03:15:41 PM INFO: Successfully loaded problem
11/18/2023 03:15:41 PM INFO: Successfully loaded test set
11/18/2023 03:15:41 PM INFO: Successfully loaded config
11/18/2023 03:15:41 PM INFO: Successfully loaded test suite
11/18/2023 03:15:41 PM INFO: Running test suite
11/18/2023 03:15:41 PM INFO: Unpacking: case_x: 1, case_y: 2, expected: 3
11/18/2023 03:15:41 PM INFO: Test passed: got 3
11/18/2023 03:15:41 PM INFO: Unpacking: case_x: 3, case_y: 4, expected: 7
11/18/2023 03:15:41 PM INFO: Test passed: got 7
11/18/2023 03:15:41 PM INFO: Unpacking: case_x: 5, case_y: 6, expected: 11
11/18/2023 03:15:41 PM INFO: Test passed: got 11
11/18/2023 03:15:41 PM INFO: Submitting to http://localhost:5000/submit
11/18/2023 03:15:41 PM INFO: Payload: {'userId': '01', 'problemId': 0, 'time': 1700300741.478954, 'status': 'pass'}
11/18/2023 03:15:41 PM INFO: Response, POST Result: 200
11/18/2023 03:15:41 PM ERROR: Failed to get next problem, Status Code: 404
11/18/2023 05:59:52 PM INFO: problem_path: /home/avs/Projects/TECHAZTRA/Server/static/rounds/round_1/problem.py, problem_language: python
11/18/2023 05:59:52 PM INFO: Selected Language: Python
11/18/2023 05:59:52 PM INFO: Successfully loaded problem
11/18/2023 05:59:52 PM INFO: Successfully loaded test set
11/18/2023 05:59:52 PM INFO: Successfully loaded config
11/18/2023 05:59:52 PM INFO: Successfully loaded test suite
11/18/2023 05:59:52 PM INFO: Running test suite
11/18/2023 05:59:52 PM INFO: Unpacking: case_x: 1, case_y: 2, expected: 3
11/18/2023 05:59:52 PM INFO: Test passed: got 3
11/18/2023 05:59:52 PM INFO: Unpacking: case_x: 3, case_y: 4, expected: 7
11/18/2023 05:59:52 PM INFO: Test passed: got 7
11/18/2023 05:59:52 PM INFO: Unpacking: case_x: 5, case_y: 6, expected: 11
11/18/2023 05:59:52 PM INFO: Test passed: got 11
11/18/2023 05:59:52 PM ERROR: Test Suite Encountered an Error: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /submit (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f46c6285490>: Failed to establish a new connection: [Errno 111] Connection refused'))
11/18/2023 06:01:56 PM INFO: problem_path: /home/avs/Projects/TECHAZTRA/Server/static/rounds/round_1/problem.py, problem_language: python
11/18/2023 06:01:56 PM INFO: Selected Language: Python
11/18/2023 06:01:56 PM INFO: Successfully loaded problem
11/18/2023 06:01:56 PM INFO: Successfully loaded test set
11/18/2023 06:01:56 PM INFO: Successfully loaded config
11/18/2023 06:01:56 PM INFO: Successfully loaded test suite
11/18/2023 06:01:56 PM INFO: Running test suite
11/18/2023 06:01:56 PM INFO: Unpacking: case_x: 1, case_y: 2, expected: 3
11/18/2023 06:01:56 PM INFO: Test passed: got 3
11/18/2023 06:01:56 PM INFO: Unpacking: case_x: 3, case_y: 4, expected: 7
11/18/2023 06:01:56 PM INFO: Test passed: got 7
11/18/2023 06:01:56 PM INFO: Unpacking: case_x: 5, case_y: 6, expected: 11
11/18/2023 06:01:56 PM INFO: Test passed: got 11
11/18/2023 06:01:56 PM ERROR: Test Suite Encountered an Error: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /submit (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa9506c94d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
